# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - we12121

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_9558e41680dd40288aa89f9872d6abbc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b7d6ba970bbd4a138a26941399a87fb7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_9558e41680dd40288aa89f9872d6abbc }}/azure:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'we12121'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_23eb546baa924eaf8ac710658e33763a }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_9558e41680dd40288aa89f9872d6abbc }}/azure:${{ github.sha }}'